### ISSUE TITLE
Staying connected (pi4) with HA integration

### ISSUE THREAD

**Issue by thephatmaster** [sopelj/python-ember-mug#3]
* Python Ember Mug version: Unknown Apologies for my ignorance. I'm using your (sopelj's) ember mug integration for home assistant.
* Python version: 3.9

* Operating System: Raspberry Pi OS

### Description

I can only get readings for my mug (v1) when it's freshly paired.

I was expecting a "live" view in HA.

I've read the point about re-pairing in the integration's repo. I don't really want to do this all the time to use my mug in HA (however it is not unusual, the android app needs constant re-pairing)

I was hoping the integration would solve the connectivity issues these mugs have with the android app.

My log shows:

```
2023-01-08 20:23:00.218 ERROR (MainThread) [custom_components.ember_mug.coordinator] EMBER ([MyEmberMAC]) - [MyEmberMAC]: Failed to connect: 
```

### What I Did

Followed the setup instructions on the repo:
- setup in app (done ages ago)
- unpaired from my phone
- pairing mode activated once HA found the device.

**Comment by sopelj** [comment]
Hey! Thanks for the info. If you're using the latest integration you should be on almost the latest version. If you're running on Rasberry Pi OS are you using a Home Assistant in docker or directly in Python? Are you using the integrated Bluetooth of the Pi or with one of the supported dongles?

That is quite strange. You should get a live view, that is the point of the integration and something this library can do directly as well.

You shouldn't need to "re-pair" the mug, nor reset it. In fact it works better if it was setup in the app initially. The only important thing is that no other device is trying to use it at the same time. 

Did you move the mug away from the Pi after setup? Is it in pairing mode (i.e is the blue light still blinking) or is it in standard mode?

Have you tried using this library directly? Or just the home assistant integration?

**Comment by thephatmaster** [comment]
> Hey! Thanks for the info. If you're using the latest integration you should be on almost the latest version.

No problem, thanks so much for the integration. It's very cool to have it in HA.

For the avoidance of doubt: this behaviour with my mug (v1 10oz white) is no different from how it behaves with the Android app. It will often disconnect from that app. To reconnect the pairing function (hold for 7 secs) needed to be used.

I'm not sure if it does this because of a firmware issue? 

> If you're running on Rasberry Pi OS are you using a Home Assistant in docker or directly in Python? 

My HA instance is HA Core in a Python venv

> Are you using the integrated Bluetooth of the Pi or with one of the supported dongles?

I'm using the Pi4's integrated Bluetooth.

> That is quite strange. You should get a live view, that is the point of the integration and something this library can do directly as well.

I've reconnected the mug this morning by holding the pairing button until Lovelace updated, and will check this out. Last time I connected the mug it worked briefly, then stayed frozen at 100% full etc. I think because the mug had disconnected itself, perhaps by going out of range, and I hadn't manually reconnected by re-pairing

> You shouldn't need to "re-pair" the mug, nor reset it. In fact it works better if it was setup in the app initially. The only important thing is that no other device is trying to use it at the same time.

As above, this seems to be standard behaviour for the v1 mug. It needed to be put back in "pairing" mode to reconnect several times a day on Android (see play store reviews about connectivity)

> Did you move the mug away from the Pi after setup? Is it in pairing mode (i.e is the blue light still blinking) or is it in standard mode?

I move the mug away once it is in standard mode and showing on my lovelace dash

> Have you tried using this library directly? Or just the home assistant integration?

I've only tried the HA integration

**Comment by sopelj** [comment]
Thanks! I hope we can iron out the kinks. 

> For the avoidance of doubt: this behaviour with my mug (v1 10oz white) is no different from how it behaves with the Android app. It will often disconnect from that app. To reconnect the pairing function (hold for 7 secs) needed to be used.

You have connectivity issues like this on the Android app as well? I don't think that's normal.  I don't have the v1 mug, but in theory it should work about the same. The app isn't the most reliable, but it worked OK as long as I was close.


> I'm not sure if it does this because of a firmware issue?

It definitely could be. Have you updated the firmware on your mug? If you're close to your phone it shouldn't disconnect randomly. As long as your phone is the only device trying to connect to it.

> My HA instance is HA Core in a Python venv
Ok, thanks. 

> I'm using the Pi4's integrated Bluetooth.
Ok, that should work. The Pi 4B is [listed as working](https://www.home-assistant.io/integrations/bluetooth/#known-working-high-performance-adapters). Not sure what the range is, but if you have the same issue with your phone then I don't think that's the problem. Can't hurt to try though if you have another to try.

> I've reconnected the mug this morning by holding the pairing button until Lovelace updated, and will check this out. Last time I connected the mug it worked briefly, then stayed frozen at 100% full etc. I think because the mug had disconnected itself, perhaps by going out of range, and I hadn't manually reconnected by re-pairing

Oh ok. I know mine has on very rare occassions disconnected and I've had to do that, but when it goes back in range it **should** reconnect by itself. Do you regularily go out of range of the Pi?

> As above, this seems to be standard behaviour for the v1 mug. It needed to be put back in "pairing" mode to reconnect several times a day on Android (see play store reviews about connectivity)

Oh OK. I did see some bad reviews of the app, so I don't know if it's a problem with the v2 as well. I didn't use it for very long.

> I move the mug away once it is in standard mode and showing on my lovelace dash

How far away do you move it? If it goes out of range it will definitely stop updating, that's normal. I'm not sure what the range of the Bluetooth on the Pi is. Perhaps try using it quite near the Pi and see if it stays connected and updates properly? The issue may simply be range/signal issues.

> I've only tried the HA integration
Ok! Well, you can run this directly on the Pi if you want to test it, but it is relatively the same as using it in Home Assistant. Perhaps try increasing the logging level to see if you get any issues from the integration though.

**Comment by sopelj** [comment]
@thephatmaster did you have any luck or make any progress?

**Comment by thephatmaster** [comment]
Hi there, thanks for the chaser,

Connection is now stable (it will reconnect when in range).

**Comment by sopelj** [comment]
Ok, perfect! I'll close this then. You can always open another issue if something else comes up.
